export const transactions = [
  {
    id: 1,
    date: "22 feb 2024",
    type: "credit",
    amount: "$10.56",
    initiator: "oluwafemi akolade",
    bank: "uba",
    acctNo: "",
    desc: "this is a test",
  },
  {
    id: 2,
    date: "22 feb 2024",
    type: "debit",
    amount: "$10.56",
    initiator: "oluwafemi akolade",
    bank: "uba",
    acctNo: "",
    desc: "this is a test",
  },
  {
    id: 3,
    date: "22 feb 2024",
    type: "credit",
    amount: "$10.56",
    initiator: "oluwafemi akolade",
    bank: "uba",
    acctNo: "",
    desc: "this is a test",
  },
];
