name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  frontend:
    name: Frontend build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: "npm"

      - name: Install frontend dependencies and build
        working-directory: client
        run: |
          npm ci
          npm run build --if-present
          npm run test

  backend:
    name: Backend Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: "npm"

      - name: Install backend dependencies and run lint
        working-directory: server
        run: |
          npm ci
          npm run lint
